export const IS_DEVELOMENT = process.env.NODE_ENV != 'production'
// IS_DEVELOMENT VA A SER TRUE SI PROCESS.ENV NO ESTA EN PRODUCCION Y SE ENCUENTRA EN DESARROLLO
// ESTO SIRVE PARA QUE SE O DESACTIVEN COSAS MIENTRAS ENTA EN DESARROLLO Y SE PASA A PRODUCCION, EN ESTE CASO EL FOOTER
